---
apiVersion: cloudbees.com/v2025.9
kind: task
metadata:
  name: qe stage task 1
spec:
  waitDependencies:
    - name: wait dependency name3
      allowSkip: true
      waitForTriggeredPipelines: true
      waitForTriggeredReleases: true
      assigneesForSkip:
        - "project: qe proj nameGenerateApplyDslSyncForWaitDependencymnJvE"
