---
apiVersion: cloudbees.com/v2025.12
kind: process
metadata:
  name: new nameGenerateApplyDslSyncForProcesseszYgxN
spec:
  credentialName: test_cred
  processType: UNDEPLOY
  timeLimit: "10"
  workingDirectory: qq
  workspaceName: default
