---
apiVersion: cloudbees.com/v2025.9
kind: acl
spec:
  inheriting: true
  aclEntries:
    - principalType: user
      principalName: qe proj nameGenerateApplyDslSyncForPluginConfigurationzyWQW
      changePermissionsPrivilege: allow
      executePrivilege: inherit
      modifyPrivilege: allow
      readPrivilege: allow
