---
apiVersion: cloudbees.com/v2025.12
kind: process
metadata:
  name: application processnew nameGenerateApplyDslSyncForProcesseszYgxN
spec:
  credentialName: test_cred
  exclusiveEnvironment: true
  processType: UNDEPLOY
  timeLimit: "10"
  workingDirectory: qq
  workspaceName: default
  formalParameters:
    - name: ec_enforceDependencies
      defaultValue: "0"
      expansionDeferred: true
      type: checkbox
