---
apiVersion: cloudbees.com/v2025.12
kind: acl
spec:
  inheriting: false
  aclEntries:
    - principalType: serviceAccount
      principalName: qe service accountGenerateApplyDslSyncForServiceAccountAfCQG
      changePermissionsPrivilege: allow
      executePrivilege: allow
      modifyPrivilege: allow
      readPrivilege: allow
    - principalType: user
      principalName: qe service accountGenerateApplyDslSyncForServiceAccountAfCQG
      changePermissionsPrivilege: allow
      executePrivilege: inherit
      modifyPrivilege: deny
      readPrivilege: deny
    - principalType: user
      principalName: qe userGenerateApplyDslSyncForServiceAccountgVypY
      changePermissionsPrivilege: allow
      executePrivilege: inherit
      modifyPrivilege: allow
      readPrivilege: allow
