---
apiVersion: cloudbees.com/v2025.12
kind: acl
spec:
  inheriting: true
  aclEntries:
    - principalType: group
      principalName: groupName
      changePermissionsPrivilege: allow
      executePrivilege: allow
      modifyPrivilege: allow
      readPrivilege: allow
    - principalType: user
      principalName: userName
      changePermissionsPrivilege: allow
      executePrivilege: allow
      modifyPrivilege: allow
      readPrivilege: allow
